title: Sajal Sharma # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <label style="font-weight: bold; font-size: large;">Engineering Lead</label>
  <br><br>
  <img style="max-width: 6%;" src="/images/education_thumbnail.png"> M.Tech, <a href="https://www.iiit.ac.in/" target="_blank" style="cursor:pointer"><label style="cursor: pointer">IIIT Hyderabad</label></a> 
  <br><br>
  <a href="https://www.linkedin.com/in/sajalsarwar/" target="_blank" style="cursor:pointer"><img style="max-width: 6%; vertical-align: text-top" src="/images/linkedin_thumbnail.png"><label style="padding-left: 2%; cursor: pointer">LinkedIn</label></a> 
  <br><br>
  <a href="/articles" style="cursor:pointer"><img style="max-width: 6%; vertical-align:middle;" src="/images/articles_thumbnail.png"><label style="padding-left: 2%; cursor: pointer">My Articles</label></a>
  <br><br>
  <a href="https://twitter.com/cosmos_sajal" target="_blank" style="cursor:pointer"><img style="max-width: 6%; vertical-align: text-top" src="/images/twitter_thumbnail.png"><label style="padding-left: 2%; cursor: pointer">Twitter</label></a>
  <br><br>
  <a href="https://www.instagram.com/sajal_cosmos/" target="_blank" style="cursor:pointer"><img style="max-width: 6%" src="/images/instagram_thumbnail.png"><label style="padding-left: 2%; cursor: pointer">Instagram</label></a>
  <br><br>
  <a href="/sajal_sharma.pdf" style="cursor:pointer" target="_blank"><img style="max-width: 6%; vertical-align:middle;" src="/images/resume_thumbnail.png"><label style="padding-left: 2%; cursor: pointer">Resume</label></a>
  <br><br>
  <a href="mailto:sajal.4591@gmail.com"><img style="max-width: 6%; vertical-align:middle;" src="/images/mail_thumbnail.png"><label style="padding-left: 2%; cursor: pointer">Contact Me</label></a>
  <br><br>
  <a href="/gatenotes" style="cursor:pointer"><label style="cursor: pointer">GATE CSE Notes</label></a>

theme: jekyll-theme-minimal
google_analytics: UA-172465513-1 # your Google Analytics tracking ID here
